### ISSUE TITLE
fire tv os 4 crash

### ISSUE THREAD

**Issue by co5mo** [romanvm/kodi.yatp#11]
hi roman

I cant run your torrent client when using rarbg tv shows addon

log here: http://pastebin.com/PmmGPWfE error propably at line 732

can you please look into this, let me know if you need any more details thanks.

**Comment by romanvm** [comment]
You have disabled the YATP torrent engine in plugin settigns (line #380).

**Comment by co5mo** [comment]
it works, thank you so much I didn't know it is necessary! btw great addon I use rarbg all the time :+1:

**Comment by co5mo** [comment]
will you fork pulsar so it uses your much stable torrent client?

**Comment by romanvm** [comment]
I don't use Pulsar and I'm not interested in developing it.

**Comment by co5mo** [comment]
do you use yatp for movies too? I am looking for yify/yts addon that uses your client
