### ISSUE TITLE
How can I call yatp?

### ISSUE THREAD

**Issue by dentaku65** [romanvm/kodi.yatp#13]
Hello,
I have a script used to play .torrent automatically
https://raw.githubusercontent.com/Zanzibar82/plugin.video.streamondemand/master/servers/torrent.py

How can I call yatp to play?

snip
---------------------------
    media_url_xbmctorrent = "plugin://plugin.video.xbmctorrent/play/%s" % urllib.quote_plus(link)
    media_url_pulsar = "plugin://plugin.video.pulsar/play?uri=%s" % urllib.quote_plus(link)
    media_url_stream = "plugin://plugin.video.stream/play/%s" % urllib.quote_plus(link)

    video_urls = [
         [ "[xbmctorrent] %s" % (name), media_url_xbmctorrent ],
         [ "[pulsar] %s" % (name), media_url_pulsar ],
         [ "[stream] %s" % (name), media_url_stream ]

----------------------------------------------------

TIA
Den

**Comment by romanvm** [comment]
Please read [project's Wiki](https://github.com/romanvm/kodi.yatp/wiki). It includes info on YATP API.

**Comment by dentaku65** [comment]
ok thank you Roman, got it.
