### ISSUE TITLE
Problem with streaming

### ISSUE THREAD

**Issue by zewelor** [romanvm/kodi.yatp#15]
Hi

thanks for this excellent plugin ! I was testing it and got some strange behaviour, not sure if my settings are wrong or there is a bug. When I start playing some movie, there is initial buffering to start playback, after it completes movie start. When looking at web UI there is total DL, for example 30 MB, but the state of torrent is finished / and % is 100%, and download stops. When player runs out of buffer, torrent completed % changes to 99% and downloading starts again. After downloading missing chunks movie plays, and torrent download stops again, till next missing chunk. 

Expected behaviour - after starting playback yapt keeps downloading till 100% of data is downloaded, and % indicator counts downloaded data correctly

Tested on version 3.0.8

**Comment by romanvm** [comment]
Where is your [Kodi debug log](http://kodi.wiki/view/Log_file) for the issue?

**Comment by zewelor** [comment]
http://pastebin.com/A1m0yUs5 
torrent url: http://www.frostclick.com/torrents/video/animation/Big_Buck_Bunny_1080p_surround_frostclick.com_frostwire.com.torrent
I'm using openelec 6.0 on rpi2

**Comment by romanvm** [comment]
This torrent works fine on my side (except for poor download speed, but this is not a YATP's issue), and I don't see any specific problems in the log.

I've noticed that you are using Raspberry Pi. Do you have enough storage space on the disk where you have set YATP download location? YATP works as a regular torrent client (and can be used as one), so it requires enough space for torrent downloads.

**Comment by zewelor** [comment]
I'm using nfs mounted share as download directory. It has plenty of free space. I've tested also some other torrents and behaviour is the same. In web ui torrent is marked as finished after initial buffering and download stops until missing chunk needs to be played, then complete percentage goes back to 95% or something like that, few more MBs are being downloaded, until 100% percent is reached again and playback resume until next missing chunks and etc. I've tried some tv show and it worked fine. Yatp kept downloading until whole episode was downloaded.

**Comment by romanvm** [comment]
Again, I cannot reproduce any issue, at least with the torrent link you gave above. As for download % value in the web-UI, it is mentioned in the "Known issues" section of the project's Wiki.

**Comment by zewelor** [comment]
After more testing I think problem is with slow download speeds and no port forwarding which I have turned on now, also I've changes connection limit to 300, and tried smaller files, it seems to work. I was also misguided by web ui percentage bug. I'm closing this, thanks for taking care :)
