### ISSUE TITLE
AndroidTV (5.1)

### ISSUE THREAD

**Issue by lcohen999** [romanvm/kodi.yatp#16]
YATP does not seem to work with the nvidia shield.

Happy to post a log if you have time to look at it.

It fails when the daemon tries to start

**Comment by romanvm** [comment]
Log is the first thing that needs to be posted. Also working on Android is not guaranteed. See the project's Wiki on that matter.

**Comment by lcohen999** [comment]
I will post the log when I get home tonight.   

I completely understand that (Android)  was just hoping, depending on the issue, it could be made to work.

**Comment by lcohen999** [comment]
pastebin as promised 

http://pastebin.com/AnDnQNdW

**Comment by romanvm** [comment]
That's what I was afraid of -  binary `libtorrent` module cannot be imported on your particular Android system. Since working with binary modules is seriously broken in Kodi-Pyhton for Android, there's nothing I can do here.
