### ISSUE TITLE
Do I need to have room for the full video file?

### ISSUE THREAD

**Issue by john3voltas** [romanvm/kodi.yatp#22]
From reading the wiki I understand that YATP uses the sliding window approach which allows it to start playing a video file even though it hasn't downloaded the full video file.
But, in order to watch the full video file, do I need to have room to accommodate the whole video file?
For instance, if a torrent has a video file with 4GB and my HDD only has 2GB of free disk space, will I be able to watch the whole video?
Or having the sliding window only allows me to start watching it before it downloads the whole video but nevertheless I still need to have room for the whole video file?

**Comment by romanvm** [comment]
I thought it was clear enough that when the sliding window reaches the end of a videofile all its pieces will be downloaded. But yes, you need full space for the videofile you are watching.

**Comment by john3voltas** [comment]
Okay, let me break that in two pieces. You say that in the end it will have downloaded the full video file but what if I don't have room for the whole file?
The reason I'm asking is because I'm on an old Android tv box which doesn't have much room for downloads and my sdcard is very small. I can only get 5 or 6 hq movies on it and I wouldn't want to be connecting a usb hdd to it.
Thanks, man.

**Comment by romanvm** [comment]
Honestly, I've never tested such scenario, but If there is not enough space on your disk, some error condition will occur and download will be stopped one way or another. Disk operations are controlled by the underlying libtorrent library which is a "black box" for me.

**Comment by john3voltas** [comment]
No problem.
I guess I'll have to find a better way to store my video files on my tv box because the sdcard is too small and too slow...
You can now close this one too.
Thanks, man. :smile:
