### ISSUE TITLE
How to watch a video that I selected for download?

### ISSUE THREAD

**Issue by john3voltas** [romanvm/kodi.yatp#23]
There's the option to "play a torrent" and the option to "download a torrent".
Is it possible to start watching a torrent that is downloading before the download comes to an end? There's a place where I can see the torrents but when I open one of them it shows me it's downloading&uploading status. It doesn't let me play that torrent or at least I didn't find a way to do it.

**Comment by romanvm** [comment]
Indeed, in-Kodi UI requires reworking and I've even opened an issue in this tracker for that. I will get to that as soon as I have enough time. But you can still play the same .torrent file that you have added for downloading. You can add the same torrents to YATP repeatedly. There are no side effects from that except that when you start playing a torrent that you have already added for downloading, download for that torrent will stop, and only the videofile you are playing will be downloaded. Currently you can restore downloading for such 'finished' torrents only from the web-UI.

**Comment by john3voltas** [comment]
Thanks for the adding-the-same-torrent tip. Indeed it works.
Got a question regarding that. If my download has just reached 50% and re-add the same torrent in "play mode" does it use the 50% which were already downloaded? Or does it just start the download from the beginning?
Is there a more proper place to be asking these questions?
Can these tips be added to the wiki?
Thanks man :)

**Comment by romanvm** [comment]
Yes, all downloaded pieces will be used. The sliding window simply skips existing pieces and tries to download only missing ones. If a whole video is downloaded, playback will start immediately without buffering.

As for the place for asking questions, I guess this will do (the tracker even has "help needed" label for an issue), but I will add a link to the respective thread on Kodi forum.

Also, as I've said, I'm going to re-work the in-Kodi UI so re-adding the same torrent won't be necessary.

**Comment by john3voltas** [comment]
I guess you can now close this one.
Thanks mate :smile:
