### ISSUE TITLE
some torrents wont download

### ISSUE THREAD

**Issue by HengeDK** [romanvm/kodi.yatp#27]
sorry for missing log file

https://www.dropbox.com/s/n5crfhavn4d2pbs/kodi.log?dl=0

nothing happens in download

**Comment by romanvm** [comment]
This is not a debug log and it has no info about any possible issues with YATP. Also please use any of pastebin sites available, e.g. xbmclogs.com.

**Comment by romanvm** [comment]
Since the issue opener hasn't provided any more info, I'm closing it.
