### ISSUE TITLE
List .torrent files from FTP server shortcut [Feature Request]

### ISSUE THREAD

**Issue by Zaptor** [romanvm/kodi.yatp#28]
Hi there,

I'm trying to find an easy interface that my parents could use. I would like to put .torrent files on my FTP server and have my parents kodi only show that list as an option to stream from.

Is this something that already exists on another add-on or would it be possible to add this?

Thanks for your time.

**Comment by romanvm** [comment]
Sorry, but YATP does not support online torrent listing of any kinds and never will.
