### ISSUE TITLE
Transdroid support

### ISSUE THREAD

**Issue by co5mo** [romanvm/kodi.yatp#30]
hi roman,

is there a way to add yatp to transdrone app? http://www.transdroid.org/ or https://play.google.com/store/apps/details?id=org.transdroid.lite

I want to use it to remotely add magnet links to yatp from my phone. I can connect to the server using my phone browser but the app can't seem to connect. Is there any special settings I can use?
I have selected rtorrent client, correct port but it refuses to connect.
It would be useful to start torrent from phone when clicking on magnet as Transdroid/Transdrone has its own open with intent

I also tried windows rtorrent gui ntorrnet that also can't connect

thanks

**Comment by romanvm** [comment]
Currently starting playback is supported only from other Kodi plugins via `plugin://` protocol. General torrent management is possible remotely via json-rpc. All this is covered in the project's Wiki.

And what does rtorrent have to do with this?

**Comment by co5mo** [comment]
it would not serve as starting playback this would need to be added to yatse for example it would just add torrent to the libtrorrent part of yatp using Transdroid as it can manage various clients

Transdroid doesn't currently have libtorrent profile so I tough rtorrent was closest an it could work

**Comment by romanvm** [comment]
libtorrent is a rather low-level library and has nothing to do with managing torrents from user's perspective. YATP is a completely independent project and has its own management protocol based on json-rpc.

**Comment by co5mo** [comment]
ok didn't know that thanks for clarifying
