### ISSUE TITLE
[Feature Request] Plex Media Server Support

### ISSUE THREAD

**Issue by Zaptor** [romanvm/kodi.yatp#31]
Would it be possible to port YATP to a plex media server bundle for x86 windows? I believe plex is a fork of xbmc many years ago.

https://github.com/plexinc-plugins

**Comment by romanvm** [comment]
I hardly know what Plex media sever is, so I have absolutely no interest in supporting it. The core YATP code is under GPL, so naturally I don't mind if somebody else does it, as long as they respect license terms.
