### ISSUE TITLE
SPMC support?

### ISSUE THREAD

**Issue by kingdingaling83** [romanvm/kodi.yatp#44]
really love what i've read about this addon. 

What is the likelihood of this getting SPMC support? 

If you are submitting a bug report, please provide the following information.
All items are mandatory!
-->
- [ ] System description and Kodi version: SPMC

- [ ] Detailed description of the bug:
i'd really love to move from Quasar to YATP

- [ ] A link to a Kodi debug log or a screenshot if this is a cosmetic bug in the user interface:
not needed

**Comment by romanvm** [comment]
YATP by itself does not have any platform-dependent code. Support for various platforms is provided by a third-party library of pre-build binary `libtorrent` modules. It's completely up to the library maintainers to build a `libtorrent` module for a specific platform.
