### ISSUE TITLE
some minor improvements

### ISSUE THREAD

**Issue by nix87** [romanvm/kodi.yatp#45]
Hi. I just installed YATP and I already love it. It's easy to use and what is most important for me it have great control over your torrents. Seeding, watching downloaded everything is there. I'm using YATP in combination with Mancuniancol's magnetic providers and all I can say is try it cause it gives you ultimate streaming torrents experiance on Kodi. This addon got everything what one torrent streaming player needs to have and there is almost non major thing that should be done to YATP. 

If it's not a problem I have minor requests for some improvements though?

1. So far when video starts and you press pause there is no info about speed of current download or how many % left for movie to be downloaded. It wil be nice to have that especially to know if dl speed fells during your watching. 

2. Can you replace torrent name with original movie/tv show episode name. It will be easier to find subbtitles then?

**Comment by romanvm** [comment]
Thanks. Regarding your requests:

1. Video playback is controlled by Kodi core functionality. YATP cannot know if playback is paused or not. Technically, it's possible to add playback monitoring but I'm not sure if additional complexity worth it. If somebody wants to implement it, pull requests are welcomed.

2. YATP is a torrent player/client, not a data scraper or a movie/TV catalogue. It simply does not know an "original movie/episode name" the same way as uTorrent on your PC does not know it. Scrapping can be implemented in external Kodi plugins that use YATP as a player, but such functionality is outside the scope of this project.

**Comment by nix87** [comment]
Ok I understaind. As I said it's not really matters. Those are really minor stuff but I get used to this so good that I don't have problem to stay everything like that. After all through Magnetizer it's possible to add something in your library so you get already every info and artwork.
