### ISSUE TITLE
buffer issue

### ISSUE THREAD

**Issue by nix87** [romanvm/kodi.yatp#46]
Seems like any pre-buffer limit isn't enough to avoid buffering at the start of the video? Why is that?

I set my pre-buffer limit as high as I can and for movie of 6GB it went above 130MB and still I need to wait for some parts to be downloaded at the start of the video. On Quasar I use to set limit at only 50 MB for bigger size movies and is free buffer from start to begining. Why YATP bufferin so much at the start of the video?

**Comment by romanvm** [comment]
Well, YATP is not Quasar. It uses its own algorithm that guarantees delivery of all pieces necessary for playback. If some pieces in the torrent are stalled, that is, have fewer seeds to be delivered in time, YATP will wait for those pieces. This has nothing to do with the initial buffer size, only with the properties of the torrent itself.

**Comment by nix87** [comment]
Thanks for answer. I really like YATP and I connected him with Mancu's Magnetizer.. it works great.

What you think will increasing speed of internet from my ISP would help. So far I have 10Mb/s download connection from tomorrow I should have 20 Mb/s, that's double? I hope it will help. :)

**Comment by romanvm** [comment]
Increasing Internet speed should help because necessary pieces will be downloaded faster. I also have some ideas how to reduce frequent pausing on missing pieces but I need to test them first.

**Comment by romanvm** [comment]
I have released v.3.3.0 in which the frequency of pausing on missing pieces is reduced. Now YATP tries to wait for a missing piece without a pausing first and then pauses only if the piece is really stalled.
