### ISSUE TITLE
Trakt integration?

### ISSUE THREAD

**Issue by herrwusel** [romanvm/kodi.yatp#47]
Hi there,
I really enjoy using YATP and I wanted to ask if you have planned trakt integration?

**Comment by romanvm** [comment]
YATP is a general purpose torrent client and streamer for Kodi. It's not tied to any specific site or content type. So I don't see how Trakt fits into this project's concept.

**Comment by herrwusel** [comment]
You're totally right. I was a bit confused earlier.
