### ISSUE TITLE
question about yatp

### ISSUE THREAD

**Issue by lyanko** [romanvm/kodi.yatp#49]
Hi, I hope I won't be rude if a aks something developer of YATP. If he don't like my question please just ignore it and delete it I understaind and sorry in advance.

First of all great job on this addon it's really nice and smooth as a torrent player but I like more to use Quasar because it have Trakt integration and all those poster for movies and thumbs and other stuff but Quasar won't play torrents from private trackers and I don't why. I asked developer of Quasar why he have problem with private torrents and so far he can't get it why too. I notice that YATP on the other hand plays private torrents without any problem. So my question is why Quasar can't play torrents from private tracker and is there something what can be done to make it possible to do that?

I made one test for both addons. I downloaded one same torrent from one private tracker and try to play it directly through addons and here is the results.

YATP - http://paste.ubuntu.com/23667305/
Quasar - http://paste.ubuntu.com/23667315/

Is there something what developer of YATP can notice what Quasar should be done and he's not doing that? I can tell just on YATP stream starts after bufering and on Quasar it seems that something blocks torrent? Quasar just stuck on finding and can't start buffer cause he can't connect to the seeders? 
But with magnet links everything is allright, it starts buffer rught away and then streaming torrent. But private tracker don't use magnets only torrent files and I think that might be the reason why Quasar struggles with private trackers?

**Comment by lyanko** [comment]
Hi nevermind problem is solved yesterday :)

**Comment by romanvm** [comment]
First of all, regular logs are not informative at all. For Kodi troubleshooting you should (I'd say must) always use debug logs.

As for YATP vs Quasar differences, as far as I know, Quasar torrent engine is written in Go (Golang) and I don't know this language at all. So I cannot tell anything about its internal working. I know that it uses `libtorrent` library too which does support remote `.torrent` files. So I have absolutely no idea why Quasar does not support them.
