### ISSUE TITLE
Sound glitching on android tv when playing the file trough YATP

### ISSUE THREAD

**Issue by thim0o** [romanvm/kodi.yatp#52]
When i open any downloaded video trough YATP in kodi on android tv the sound is glitching. It goes like this: first 5 seconds sound working, then about 5 seconds not working and then working for a few seconds again. Is anyone else having this issue aswell?

**Comment by romanvm** [comment]
Technically, YATP by itself does not play anything. It passes a playable link to the Kodi player and then its job is done. I'm closing this issue as not relevant to YATP plugin and there's nothing I can do here.
