### ISSUE TITLE
It is possible to use with private trackers?

### ISSUE THREAD

**Issue by mancuniancol** [romanvm/kodi.yatp#8]
How could I send the information for credentials or the cookies?

**Comment by romanvm** [comment]
I'm not sure what you mean. YATP does not work with torrent sites directly, it's a pure torrent-client with streaming capabilities. You don't enter any credentials e.g. in uTorrent/Transmission/Deluge etc., so the same is here.

**Comment by mancuniancol** [comment]
My point is that I have a torrent that I want to download or play with yatp. It is hosted in a private tracker. My problem is that I can open a authenticated session and have access. But, in the moment that I send the torrent to YATP, I lose the session and the yatp is blocked for the private tracker.
I think that it could work if it is possible to send the cookies, in that way, the session will remain opened.

**Comment by romanvm** [comment]
Alternatively, you can download a .torrent file to a temp location and then pass it to YATP. Anyway, I have implemented passing cookies along with .torrent URL, but I'm not sure how it will work, though.

**Comment by mancuniancol** [comment]
Good, I will try it.  Thanks
